import type { Flight } from "./types";

export const mockFlights: Flight[] = [
  {
    id: "1",
    airline: "Vietnam Airline",
    from: "Hanoi, Vietnam",
    to: "Ho Chi Minh City, Vietnam",
    departureTime: "07:00",
    arrivalTime: "05:00",
    departureDate: "Fri 16 Jan",
    arrivalDate: "Fri 16 Jan",
    duration: "9h 15m",
    stops: 1,
    price: 900,
    baggage: "1×23kg",
    facilities: ["food", "entertainment", "wifi"],
  },
  {
    id: "2",
    airline: "Vietnam Airline",
    from: "Hanoi, Vietnam",
    to: "Ho Chi Minh City, Vietnam",
    departureTime: "07:00",
    arrivalTime: "05:00",
    departureDate: "Fri 16 Jan",
    arrivalDate: "Fri 16 Jan",
    duration: "9h 15m",
    stops: 1,
    price: 900,
    baggage: "1×23kg",
    facilities: ["food", "entertainment"],
  },
  {
    id: "3",
    airline: "VietJet Air",
    from: "Hanoi, Vietnam",
    to: "Ho Chi Minh City, Vietnam",
    departureTime: "09:30",
    arrivalTime: "11:45",
    departureDate: "Fri 16 Jan",
    arrivalDate: "Fri 16 Jan",
    duration: "2h 15m",
    stops: 0,
    price: 450,
    baggage: "1×20kg",
    facilities: ["wifi", "socket"],
  },
  {
    id: "4",
    airline: "Bamboo Airways",
    from: "Hanoi, Vietnam",
    to: "Ho Chi Minh City, Vietnam",
    departureTime: "14:00",
    arrivalTime: "16:15",
    departureDate: "Fri 16 Jan",
    arrivalDate: "Fri 16 Jan",
    duration: "2h 15m",
    stops: 0,
    price: 550,
    baggage: "1×23kg",
    facilities: ["food", "wifi", "entertainment"],
  },
];
